### ISSUE TITLE
Next Part

### ISSUE THREAD

**Issue by Brick7Face** [SpencerCornish/Paint-prog#3]
Do For next Lab:

Due: Tuesday February 23rd (two weeks)......BUT note that next Tuesday you will be given another outlab on linked lists that is a very tricky lab. Both labs will be due Feb. 23rd. but next week's lab will take up most of next week so you will need to do most of the work for this lab THIS WEEK. 

To Do:
- [x] Everything from the first requirements, inlab last week.
- [x] A way to change the color you are drawing with, sliders or JColorChooser and a swatch to show the color.
- [x] Use the ImageBuffer class that fixes repainting, backgrounds, easy clearing, etc. etc.
- [x] Get the graphics for drawing on your buttons and draw the shapes on the buttons instead of words. 
- [x ] setActionCommands so you can tell what buttons are being clicked. This example I will show on next lecture.
- [x] Space your buttons so they look centered and nice for the user (also on the next lecture, button graphic example).

**Comment by SpencerCornish** [comment]
>  setActionCommands so you can tell what buttons are being clicked. This example I will show on next lecture. 

Have we done this yet? I honestly have no idea tbh

**Comment by Brick7Face** [comment]
Idk either. I guess we'll just see when we get to class...maybe

**Comment by SpencerCornish** [comment]
I'm guessing that we have set our Action Commands... Marked as complete.
